src/Entity/Restaurante.php
<?php

namespace App\Entity;

use App\Repository\RestauranteRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: RestauranteRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Restaurante implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $cod_res = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = ['ROLE_RESTAURANTE'];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(type: 'boolean')]
    private $isVerified = false;

    #[ORM\Column(length: 45)]
    private ?string $pais = null;

    #[ORM\Column]
    private ?int $cp = null;

    #[ORM\Column(length: 45)]
    private ?string $ciudad = null;

    #[ORM\Column(length: 200)]
    private ?string $direccion = null;

    public function getId(): ?int
    {
        return $this->cod_res;
    }
    
    public function getCod_res(): ?int
    {
        return $this->cod_res;
    }
    public function getCodRes(): ?int
    {
        return $this->cod_res;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_RESTAURANTE';

        return array_unique($roles);
    }

    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): static
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getPais(): ?string
    {
        return $this->pais;
    }

    public function setPais(string $pais): static
    {
        $this->pais = $pais;

        return $this;
    }

    public function getCp(): ?int
    {
        return $this->cp;
    }

    public function setCp(int $cp): static
    {
        $this->cp = $cp;

        return $this;
    }

    public function getCiudad(): ?string
    {
        return $this->ciudad;
    }

    public function setCiudad(string $ciudad): static
    {
        $this->ciudad = $ciudad;

        return $this;
    }

    public function getDireccion(): ?string
    {
        return $this->direccion;
    }

    public function setDireccion(string $direccion): static
    {
        $this->direccion = $direccion;

        return $this;
    }
}

templates/restaurante/_delete_form.html.twig
<form method="post" action="{{ path('app_restaurante_delete', {'cod_res': restaurante.cod_res}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ restaurante.cod_res) }}">
    <button class="btn">Delete</button>
</form>

templates/restaurante/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Guardar') }}</button>
{{ form_end(form) }}

templates/restaurante/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Restaurante{% endblock %}

{% block body %}
    <h1>Edit Restaurante</h1>

    {{ include('restaurante/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_restaurante_index_admin') }}">Cancelar</a>

    {{ include('restaurante/_delete_form.html.twig') }}
{% endblock %}

templates/restaurante/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restaurante{% endblock %}

{% block body %}
    <h1>Restaurante</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Cod_res</th>
                <th>Email</th>
                <th>Roles</th>
                <th>Contraseña</th>
                <th>Verificado</th>
                <th>Opciones</th>
            </tr>
        </thead>
        <tbody>
        {% for restaurante in restaurantes %}
            <tr>
                <td>{{ restaurante.codRes }}</td>
                <td>{{ restaurante.email }}</td>
                <td>{{ restaurante.roles ? restaurante.roles|json_encode : '' }}</td>
                <td>{{ restaurante.password }}</td>
                <td>{{ restaurante.isVerified ? 'Si' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_restaurante_show', {'cod_res': restaurante.cod_res}) }}">show</a>
                    <a href="{{ path('app_restaurante_edit', {'cod_res': restaurante.cod_res}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">No hay resultados</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_restaurante_new') }}">Crear uno nuevo</a>
{% endblock %}

templates/restaurante/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Restaurante{% endblock %}

{% block body %}
    <h1>Crear uno nuevo Restaurante</h1>

    {{ include('restaurante/_form.html.twig') }}

    <a href="{{ path('app_restaurante_index') }}">Volver</a>
{% endblock %}

templates/restaurante/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Restaurante{% endblock %}

{% block body %}
    <h1>Restaurante</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Cod_res</th>
                <td>{{ restaurante.codRes }}</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>{{ restaurante.email }}</td>
            </tr>
            <tr>
                <th>Roles</th>
                <td>{{ restaurante.roles ? restaurante.roles|json_encode : '' }}</td>
            </tr>
            <tr>
                <th>Contraseña</th>
                <td>{{ restaurante.password }}</td>
            </tr>
            <tr>
                <th>Verificado</th>
                <td>{{ restaurante.isVerified ? 'Si' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_restaurante_index') }}">Volver</a>

    <a href="{{ path('app_restaurante_edit', {'cod_res': restaurante.cod_res}) }}">edit</a>

    {{ include('restaurante/_delete_form.html.twig') }}
{% endblock %}